### ISSUE TITLE
Undefined constant Elementor\Controls_Manager::ALER on 3.2.1

### ISSUE THREAD

**Issue by dieptang** [elementor/hello-theme#436]
Hi,

After auto updated to 3.2.1, My site got error: 

`Fatal error: Uncaught Error: Undefined constant Elementor\Controls_Manager::ALERT in /home/yjiltjqo/public_html/wp-content/themes/hello-elementor/includes/settings/settings-header.php:87 Stack trace: #0 /home/yjiltjqo/public_html/wp-content/plugins/elementor/core/kits/documents/tabs/tab-base.php(43): HelloElementor\Includes\Settings\Settings_Header->register_tab_controls() #1 /home/yjiltjqo/public_html/wp-content/plugins/elementor/core/kits/documents/kit.php(149): Elementor\Core\Kits\Documents\Tabs\Tab_Base->register_controls() #2 /home/yjiltjqo/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2358): Elementor\Core\Kits\Documents\Kit->register_controls() #3 /home/yjiltjqo/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(541): Elementor\Controls_Stack->init_controls() #4 /home/yjiltjqo/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(313): Elementor\Controls_Stack->get_stack() #5 /home/yjiltjqo/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2445): Elementor\Controls_Stack->get_controls() #6 /home/yjiltjqo/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(1130): Elementor\Controls_Stack->sanitize_settings() #7 /home/yjiltjqo/public_html/wp-content/plugins/elementor/includes/base/controls-stack.php(2190): Elementor\Controls_Stack->get_data() #8 /home/yjiltjqo/public_html/wp-content/plugins/elementor/core/base/base-object.php(142): Elementor\Controls_Stack->get_init_settings() #9 /home/yjiltjqo/public_html/wp-content/plugins/elementor/core/base/base-object.php(40): Elementor\Core\Base\Base_Object->ensure_settings() #10 /home/yjiltjqo/public_html/wp-content/plugins/elementor/core/kits/manager.php(117): Elementor\Core\Base\Base_Object->get_settings() #11 /home/yjiltjqo/public_html/wp-content/plugins/elementor/modules/page-templates/module.php(92): Elementor\Core\Kits\Manager->get_current_settings() #12 /home/yjiltjqo/public_html/wp-includes/class-wp-hook.php(324): Elementor\Modules\PageTemplates\Module->template_include() #13 /home/yjiltjqo/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters() #14 /home/yjiltjqo/public_html/wp-includes/template-loader.php(104): apply_filters() #15 /home/yjiltjqo/public_html/wp-blog-header.php(19): require_once('/home/yjiltjqo/...') #16 /home/yjiltjqo/public_html/index.php(17): require('/home/yjiltjqo/...') #17 {main} thrown in /home/yjiltjqo/public_html/wp-content/themes/hello-elementor/includes/settings/settings-header.php on line 87`

**Comment by rami-elementor** [comment]
@dieptang you are using an old Elementor version. Hello Theme 3.2 uses the [Alert Control](https://developers.elementor.com/docs/editor-controls/control-alert/) which was introduced in [Elementor 3.19](https://developers.elementor.com/elementor-3-19-developers-update/).
